services:
  db:
    container_name: db  
    image: mysql:latest 
    environment:
      MY_SQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_DATABASE: "earthquake_db" 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

  goapp:
    container_name: goapp
    #image: goapp:1.0.0
    build: 
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      #DATABASE_URL: mysql://root:root@db:3306/earthquake_db 
      DATABASE_URL: root:root@tcp(db:3306)/earthquake_db
    ports:
      - '8080:8080'
    depends_on:
      - db
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - goapp

volumes:
  pgdata: {}
  mysql_data: 
  

