# fly.toml app configuration file generated for earthquake-globe-web-0wajea on 2025-02-10T18:16:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'earthquake-globe-web-0wajea'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.20'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
